{
 "title": "Photovoltaik-Influx",
 "time": { "from": "now/d+5h", "to": "now" },
 "panels": [
  {
   "title": "Total produced kWh",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "select": [
      [
       { "params": [ "stats_total_yield" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Operation Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "select": [
      [
       { "params": [ "stats_total_operation_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total self consumption",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "select": [
      [
       {
        "params": [
         "stats_total_self_consumption_kwh"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total self consumption rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "select": [
      [
       {
        "params": [
         "stats_total_self_consumption_rate"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total degree of self sufficiency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "select": [
      [
       {
        "params": [
         "stats_total_degree_of_self_sufficiency"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Home Consumption",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "select": [
      [
       {
        "params": [
         "stats_total_total_home_consumption"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Input/Output",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Power Input",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "select": [
      [
       { "params": [ "pv_generator_dc_input_1_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid Feed In",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "select": [
      [
       { "params": [ "pv_generator_dc_input_1_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "- mean(\"house_home_consumption_covered_by_solar_generator\")"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "SELECT mean(\"house_home_consumption_covered_by_solar_generator\") AS \"\"a\"\", mean(\"house_home_consumption_covered_by_grid\") FROM \"pvwr\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "house_home_consumption_covered_by_solar_generator"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "by Solar" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "house_home_consumption_covered_by_grid"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "by Grid" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Todays total yield",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "select": [
      [
       { "params": [ "stats_day_yield" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today Home Consumption",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "select": [
      [
       {
        "params": [
         "stats_day_total_home_consumption"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Todays Self Consumption",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "select": [
      [
       { "params": [ "stats_day_self_consumption_kwh" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Todays Self Consumption Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "select": [
      [
       {
        "params": [
         "stats_day_self_consumption_rate"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Todays Degree Of Self Sufficiency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "select": [
      [
       {
        "params": [
         "stats_day_degree_of_self_sufficiency"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Power",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Production",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "SELECT non_negative_derivative(last(\"stats_total_yield\"), 1d) FROM \"pvwr\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "stats_total_yield" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1d" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Consumption",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "SELECT non_negative_derivative(last(\"stats_total_yield\"), 1d) FROM \"pvwr\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "stats_total_self_consumption_kwh"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1d" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Home Consumption",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "kWh per day",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "SELECT non_negative_derivative(last(\"stats_total_yield\"), 1d) FROM \"pvwr\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "stats_total_total_home_consumption"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1d" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weekly Power",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Production",
     "groupBy": [
      { "params": [ "1w" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "SELECT non_negative_derivative(last(\"stats_total_yield\"), 30d) FROM \"pvwr\" WHERE $timeFilter GROUP BY time(30d) fill(null)",
     "select": [
      [
       { "params": [ "stats_total_yield" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1w" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Consumption",
     "groupBy": [
      { "params": [ "1w" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "SELECT non_negative_derivative(last(\"stats_total_self_consumption_rate\"), 30d) FROM \"pvwr\" WHERE $timeFilter GROUP BY time(30d) fill(null)",
     "select": [
      [
       {
        "params": [
         "stats_total_self_consumption_kwh"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1w" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weekly Home",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "kWh per week",
     "groupBy": [
      { "params": [ "1w" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "SELECT non_negative_derivative(last(\"stats_total_yield\"), 1mo) FROM \"pvwr\" WHERE $timeFilter GROUP BY time(1mo) fill(null)",
     "select": [
      [
       {
        "params": [
         "stats_total_total_home_consumption"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1w" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Monthly Power",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Production",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "SELECT non_negative_derivative(last(\"stats_total_yield\"), 30d) FROM \"pvwr\" WHERE $timeFilter GROUP BY time(30d) fill(null)",
     "select": [
      [
       { "params": [ "stats_total_yield" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "30d" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Consumption",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "SELECT non_negative_derivative(last(\"stats_total_self_consumption_rate\"), 30d) FROM \"pvwr\" WHERE $timeFilter GROUP BY time(30d) fill(null)",
     "select": [
      [
       {
        "params": [
         "stats_total_self_consumption_kwh"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "30d" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Monthly Home",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "kWh per 30d",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "SELECT non_negative_derivative(last(\"stats_total_yield\"), 1mo) FROM \"pvwr\" WHERE $timeFilter GROUP BY time(1mo) fill(null)",
     "select": [
      [
       {
        "params": [
         "stats_total_total_home_consumption"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "30d" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  }
 ]
}