{
 "title": "Photovoltaik",
 "time": { "from": "now-1d/d", "to": "now-1d/d" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total produced kWh",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(stats_total_yield) AS \"stats_total_yield\"\nFROM pvwr\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Operation Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(stats_total_operation_time) AS \"stats_total_operation_time\"\nFROM pvwr\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total self consumption",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(stats_total_self_consumption_kwh) AS \"stats_total_self_consumption_kwh\"\nFROM pvwr\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total self consumption rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(stats_total_self_consumption_rate) AS \"stats_total_self_consumption_rate\"\nFROM pvwr\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total degree of self sufficiency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(stats_total_degree_of_self_sufficiency) AS \"stats_total_degree_of_self_sufficiency\"\nFROM pvwr\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Home Consumption",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(stats_total_total_home_consumption) AS \"stats_total_total_home_consumption\"\nFROM pvwr\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Power Input/Output",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  avg(pv_generator_dc_input_1_power) AS \"Power Input\"\nFROM pvwr\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(pv_generator_dc_input_1_power - house_home_consumption_covered_by_solar_generator) AS \"Grid Feed In\"\nFROM pvwr\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(house_home_consumption_covered_by_solar_generator) AS \"by Solar\",\n  avg(house_home_consumption_covered_by_grid) AS \"by Grid\"\nFROM pvwr\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Todays total yield",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(stats_day_yield) AS \"stats_day_yield\"\nFROM pvwr\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Today Home Consumption",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(stats_day_total_home_consumption) AS \"stats_day_total_home_consumption\"\nFROM pvwr\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Todays Self Consumption",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(stats_day_self_consumption_kwh) AS \"stats_day_self_consumption_kwh\"\nFROM pvwr\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Todays Self Consumption Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(stats_day_self_consumption_rate) AS \"stats_day_self_consumption_rate\"\nFROM pvwr\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Todays Degree Of Self Sufficiency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(stats_day_degree_of_self_sufficiency) AS \"stats_day_degree_of_self_sufficiency\"\nFROM pvwr\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}