{
 "title": "Photovoltaik-Influx",
 "time": { "from": "now/d+5h", "to": "now" },
 "panels": [
  {
   "title": "Total produced kWh",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "from(bucket: \"pv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_total_yield\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "stats_total_yield" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Operation Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "from(bucket: \"pv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_total_operation_time\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "stats_total_operation_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total self consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "from(bucket: \"pv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_total_self_consumption_kwh\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "stats_total_operation_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total self consumption rate",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "from(bucket: \"pv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_total_self_consumption_rate\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       {
        "params": [
         "stats_total_self_consumption_rate"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total degree of self sufficiency",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "from(bucket: \"pv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_total_degree_of_self_sufficiency\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       {
        "params": [
         "stats_total_self_consumption_rate"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Home Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "from(bucket: \"pv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_total_total_home_consumption\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       {
        "params": [
         "stats_total_total_home_consumption"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Input/Output",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pv_generator_dc_input_1_power\")\n  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pv_generator_dc_input_1_power\" or r[\"_field\"] == \"house_home_consumption_covered_by_solar_generator\")\n  |> pivot(\n      rowKey: [\"_time\"],\n      columnKey: [\"_field\"],\n      valueColumn: \"_value\"\n    )\n  |> map(fn: (r) => ({\n      r with\n      _value: r.pv_generator_dc_input_1_power - r.house_home_consumption_covered_by_solar_generator\n  }))\n  |> drop(columns: [\"house_home_consumption_covered_by_solar_generator\", \"pv_generator_dc_input_1_power\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "from(bucket: \"pv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"house_home_consumption_covered_by_solar_generator\")\n",
     "select": [
      [
       {
        "params": [
         "house_home_consumption_covered_by_solar_generator"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "by Solar" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "house_home_consumption_covered_by_grid"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "by Grid" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "from(bucket: \"pv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"house_home_consumption_covered_by_grid\")\n",
     "select": [
      [
       {
        "params": [
         "house_home_consumption_covered_by_solar_generator"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "by Solar" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "house_home_consumption_covered_by_grid"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "by Grid" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Todays total yield",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "from(bucket: \"pv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_day_yield\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "stats_day_yield" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today Home Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "from(bucket: \"pv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_day_total_home_consumption\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       {
        "params": [
         "stats_day_total_home_consumption"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Todays Self Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "from(bucket: \"pv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_day_self_consumption_kwh\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "stats_day_self_consumption_kwh" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Todays Self Consumption Rate",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "from(bucket: \"pv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_day_self_consumption_rate\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       {
        "params": [
         "stats_day_self_consumption_rate"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Todays Degree Of Self Sufficiency",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvwr",
     "query": "from(bucket: \"pv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_day_degree_of_self_sufficiency\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       {
        "params": [
         "stats_day_degree_of_self_sufficiency"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pv\")\n  |> range(start: -1y, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_total_yield\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> difference(nonNegative: true)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pv\")\n  |> range(start: -1y, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_total_self_consumption_kwh\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> difference(nonNegative: true)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Home Consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pv\")\n  |> range(start: -1y, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_total_total_home_consumption\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> difference(nonNegative: true)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weekly Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pv\")\n  |> range(start: -1y, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_total_yield\")\n  |> aggregateWindow(every: 1w, fn: last)\n  |> difference(nonNegative: true)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pv\")\n  |> range(start: -1y, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_total_self_consumption_kwh\")\n  |> aggregateWindow(every: 1w, fn: last)\n  |> difference(nonNegative: true)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weekly Home Consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pv\")\n  |> range(start: -1y, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_total_total_home_consumption\")\n  |> aggregateWindow(every: 1w, fn: last)\n  |> difference(nonNegative: true)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Monthly Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pv\")\n  |> range(start: -1y, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_total_yield\")\n  |> aggregateWindow(every: 1mo, fn: last)\n  |> difference(nonNegative: true)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pv\")\n  |> range(start: -1y, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_total_self_consumption_kwh\")\n  |> aggregateWindow(every: 1mo, fn: last)\n  |> difference(nonNegative: true)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Monthly Home Consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pv\")\n  |> range(start: -1y, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pvwr\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stats_total_total_home_consumption\")\n  |> aggregateWindow(every: 1mo, fn: last)\n  |> difference(nonNegative: true)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}